name: crystalvision

services:
  ollama:
    image: ollama/ollama:latest
    pull_policy: always
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  cache:
    # image: valkey/valkey:latest
    image: redis:latest
    pull_policy: always
    ports:
      - 6379:6379
    restart: unless-stopped
  vectordb:
    image: qdrant/qdrant:latest
    pull_policy: always
    ports:
      - 6333:6333 # tcp
      - 6334:6334 # grpc
    volumes:
      - vectordb:/qdrant/storage
    restart: unless-stopped
  discord-bot:
    build:
      dockerfile: docker/Dockerfile.discordbot
    environment:
      PYTHONUNBUFFERED: 1
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OLLAMA_EMBED_MODEL: ${OLLAMA_EMBED_MODEL}
      OLLAMA_CHAT_MODEL: ${OLLAMA_CHAT_MODEL}
      OLLAMA_CODE_MODEL: ${OLLAMA_CODE_MODEL}
      OLLAMA_VISION_MODEL: ${OLLAMA_VISION_MODEL}
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      OLLAMA_HOST: http://ollama:11434
      QDRANT_HOST: http://vectordb
    volumes:
      - ffdata:/app/data/
      - ./data/jtemplate/:/app/data/jtemplate/
      - type: bind
        source: ./data/prompts.json
        target: /app/data/prompts.json
      - type: bind
        source: ./data/emoji.json
        target: /app/data/emoji.json
      - type: bind
        source: ./data/corpus_uris.json
        target: /app/data/corpus_uris.json
      - type: bind
        source: ./data/cards.json
        target: /app/data/cards.json
    depends_on:
      - ollama
      - cache

volumes:
  ollama:
    external: true
  ffdata:
    external: true
  vectordb:
    external: true
