[tool.poetry]
name = "crystalvision"
version = "0.1.0"
description = "FFTCG Image Classification"
authors = ["Allonte <angelosheltie@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
opencv-contrib-python = ">=4.8.1.78"
keras-tuner = ">=1.4.5"
scikit-learn = ">=1.3.0"
scikit-image = ">=0.22.0"
pandas = ">=2.1.2"
pyarrow = ">=15.0.0"
Pillow = ">=10.1.0"
mlxtend = ">=0.23.0"
tensorflow-io = [
    {version = "*", platform="linux"},
    {version = "0.31.0", platform="win32"},
]
tensorflow = [
    {version = "*", platform="linux", extras=["and-cuda"]},
    {version = ">=2.10.1,<2.11", platform="win32"},
]
tqdm = ">=4.66.1"
aiohttp = ">=3.8.6"
aiofiles = ">=23.2.1"
urllib3 = [
    {version = "*", platform="linux"},
    {version = ">=2.0.7", platform="win32"},
]
numpy = [
    {version = "*", platform="linux"},
    {version = ">=1.26.1", platform="win32"},
]
keras = [
    {version = "*", platform="linux"},
    {version = ">=2.10.0", platform="win32"},
]


[tool.poetry.group.dev.dependencies]
pycodestyle = ">=2.11.1"
flake8 = ">=6.1.0"
pydocstyle = ">=6.3.0"
ipykernel = ">=6.26.0"
tensorboard = [
    {version = "*", platform="linux"},
    {version = "<2.11", platform="win32"},
]
pre-commit = ">=3.6.0"
black = ">=24.1.1"
ruff = ">=0.1.14"
pytest = ">=8.0.0"



[tool.poetry.group.debug.dependencies]
paretoset = ">=1.2.3"


[tool.poetry.group.labeling.dependencies]
pyqt5-qt5 = [
    {version = "*", platform="linux"},
    {version = "<=5.15.10", platform="win32"},
]
labelme = ">=5.4.1"
pyqt5 = "^5.15.10"


[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.ruff]
select = ["E", "F"]
ignore = ["E501"]
