[tool.poetry]
name = "crystalvision"
version = "0.1.0"
description = "FFTCG Image Classification"
authors = ["Allonte <angelosheltie@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
opencv-contrib-python = ">=4.8.1.78"
keras-tuner = ">=1.4.5"
scikit-learn = ">=1.3.0"
scikit-image = ">=0.22.0"
pandas = ">=2.1.2"
Pillow = ">=10.1.0"
mlxtend = ">=0.23.0"
tensorflow-io = "0.31.0"
tensorflow = "<2.11"
tqdm = "^4.66.1"
aiohttp = "^3.9.0"
aiofiles = "^23.2.1"


[tool.poetry.group.dev.dependencies]
pycodestyle = ">=2.11.1"
flake8 = ">=6.1.0"
pydocstyle = ">=6.3.0"
ipykernel = ">=6.26.0"
tensorboard = "<2.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
